"""
=========================================================
Train Hand Gesture Recognition Model
=========================================================

Purpose:
--------
This script trains a Machine Learning model using the
hand landmark dataset collected from MediaPipe.

Input:
------
dataset.csv

Output:
-------
models/gesture_model.pkl

The trained model can later be loaded by the Streamlit
application for real-time hand gesture prediction.
"""

import os
import joblib
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
)
from sklearn.model_selection import train_test_split


# =========================================================
# CONFIGURATION
# =========================================================

# Path of collected dataset
DATASET_PATH = "./dataset/dataset_AtoZ.csv" 
# "dataset.csv" is the name of the dataset file generated by the data collection script.

# Folder where trained model will be stored
MODEL_FOLDER = "./models"

# Model filename
MODEL_NAME = "gesture_AtoZ_model.pkl"

# Full model path
MODEL_PATH = os.path.join(MODEL_FOLDER, MODEL_NAME)

# Test dataset percentage
TEST_SIZE = 0.20

# Random state ensures same result every training
RANDOM_STATE = 42

# Number of trees in Random Forest
N_ESTIMATORS = 200


# =========================================================
# CREATE MODEL DIRECTORY
# =========================================================

os.makedirs(MODEL_FOLDER, exist_ok=True)


# =========================================================
# LOAD DATASET
# =========================================================

print("=" * 60)
print("Loading dataset...")
print("=" * 60)

dataset = pd.read_csv(DATASET_PATH)

print(f"Dataset Loaded Successfully")
print(f"Total Samples : {len(dataset)}")
print(f"Total Columns : {len(dataset.columns)}")

print("\nGesture Classes:")
print(dataset["label"].value_counts())


# =========================================================
# PREPARE FEATURES & LABELS
# =========================================================

print("\nPreparing training data...")

# X = Input Features (63 landmark values)
X = dataset.drop("label", axis=1)

# y = Output Label
y = dataset["label"]


# =========================================================
# SPLIT DATASET
# =========================================================

print("\nSplitting dataset...")

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=y,
)

print(f"Training Samples : {len(X_train)}")
print(f"Testing Samples  : {len(X_test)}")


# =========================================================
# CREATE MODEL
# =========================================================

print("\nCreating Random Forest Model...")

model = RandomForestClassifier(
    n_estimators=N_ESTIMATORS,
    random_state=RANDOM_STATE,
)

print("Training model...")

model.fit(X_train, y_train)

print("Training Completed Successfully.")


# =========================================================
# MODEL EVALUATION
# =========================================================

print("\nEvaluating Model...")

train_prediction = model.predict(X_train)
test_prediction = model.predict(X_test)

train_accuracy = accuracy_score(
    y_train,
    train_prediction,
)

test_accuracy = accuracy_score(
    y_test,
    test_prediction,
)

print("\n" + "=" * 60)
print("MODEL ACCURACY")
print("=" * 60)

print(f"Training Accuracy : {train_accuracy * 100:.2f}%")
print(f"Testing Accuracy  : {test_accuracy * 100:.2f}%")


# =========================================================
# CLASSIFICATION REPORT
# =========================================================

print("\n" + "=" * 60)
print("CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        test_prediction,
    )
)


# =========================================================
# CONFUSION MATRIX
# =========================================================

print("\n" + "=" * 60)
print("CONFUSION MATRIX")
print("=" * 60)

print(
    confusion_matrix(
        y_test,
        test_prediction,
    )
)


# =========================================================
# SAVE MODEL
# =========================================================

print("\nSaving model...")

joblib.dump(
    model,
    MODEL_PATH,
)

print(f"Model saved successfully.")
print(f"Location : {MODEL_PATH}")


# =========================================================
# TRAINING COMPLETED
# =========================================================

print("\n" + "=" * 60)
print("TRAINING COMPLETED SUCCESSFULLY")
print("=" * 60)